Regarding users repository and the main page
tomasskon/komandax-smart-saver pull request #12
Opened 2020-10-29 21:23 UTC by 0ever

-Added users repository (three extra columns: cash, card, userimage);
-Added ImageHelper with static ByteArrayToString function which may be useful in the future;
-Deleted the seperate repository for balances;
-Main page changes: you can now upload a profile image which is saved in the database as binary data; main page now shows total account balance;

2020-10-29 21:40 UTC, tomasskon requested changes

2020-10-29 21:40 UTC, tomasskon commented on DBScripts/1-MockBaseScript.sql
>  	[Id] [uniqueidentifier] NOT NULL,
Its a bit incorrect to remake a previous script because think about it in this way: We have already runned this script on our computers, or lets say  cloud enviroment or something. Therefore one issue is that this script wouldn't even run or another one is that it would cause exceptions because most of the elements in this script would be already created. Thats why we always create a new scripts and follow numeric naming convection to know which script to run after which if that makes sense. So solution here is to create a seperate script that would modify this table

2020-10-29 21:40 UTC, tomasskon commented on Solution/SmartSaver/BusinessLayer/HelperClasses/Balance/BalanceHelper.cs
> +        private UserRepository _userRepository;
I think it would be better to have a new line between each method just to seperate them one from each other

2020-10-29 21:40 UTC, tomasskon commented on Solution/SmartSaver/BusinessLayer/HelperClasses/Balance/BalanceHelper.cs
> +
Few empty lines here

2020-10-29 21:40 UTC, tomasskon commented on Solution/SmartSaver/BusinessLayer/HelperClasses/Images/ImageHelper.cs
> +
Same here, one empty line

2020-10-29 21:40 UTC, tomasskon commented on Solution/SmartSaver/SmartSaver.Domain/Models/User.cs
> +
Same here, few empty new lines

2020-10-29 21:40 UTC, tomasskon commented on Solution/SmartSaver/SmartSaver/Forms/UserControls/Main.cs
> +        private async void button1_Click(object sender, EventArgs e)
Maybe rename this  button to have more specific name?

2020-10-29 21:40 UTC, tomasskon commented on Solution/SmartSaver/SmartSaver/Forms/UserControls/Main.cs
> +        private void button2_Click(object sender, EventArgs e)
Same with this button

2020-10-30 07:27 UTC, tomasskon requested changes

2020-10-30 07:27 UTC, tomasskon commented on DBScripts/3-AddFieldsToUsersTable.sql
> +ALTER TABLE [dbo].[Users]
Don't know if you have seen in master but script 3 already exists

2020-10-30 08:27 UTC, 0ever commented on DBScripts/3-AddFieldsToUsersTable.sql
> +ALTER TABLE [dbo].[Users]
Order was changed, but as noted already before, it won't happen again

2020-11-01 13:38 UTC, Marius-K approved these changes

2020-11-01 14:26 UTC, aurimasjurgelis approved these changes

2020-11-01 14:35 UTC, merged