Added balance repository, updated UI to match the project structure.
tomasskon/komandax-smart-saver pull request #8
Opened 2020-10-22 09:53 UTC by 0ever

2020-10-22 12:03 UTC, 0ever commented on Solution/SmartSaver/SmartSaver.Domain/Repositories/GenericRepository.cs
> +        private SmartSaverDataContext Context = new SmartSaverDataContext(new DbContextOptionsBuilder<SmartSaverDataContext>()
čia dėl šito neveikė ankščiau duomenų įkėlimas į duombazę

2020-10-22 15:48 UTC, tomasskon requested changes

2020-10-22 15:48 UTC, tomasskon commented on DBScripts/1-MockBaseScript.sql
>  INSERT INTO [Transactions] ([Amount], [Description], [UserId]) VALUES (7, 'Buying Pizza', '6e33fa08-bc0f-438c-a21b-bcf4fc227661')
It is better to write into seperate script files. So for intance 2-AddingBalances.sql so that if somone doesn't have some table or change in their DB, they can run one specific script instead of searching the script in one big script if that makes sense.

2020-10-22 15:48 UTC, tomasskon commented on Solution/SmartSaver/BusinessLayer/HelperClasses/Balance/BalanceHelper.cs
> +
Too much spaces :D

2020-10-22 18:30 UTC, tomasskon approved these changes

2020-10-22 19:52 UTC, Marius-K approved these changes

2020-10-23 06:28 UTC, aurimasjurgelis approved these changes

2020-10-23 06:30 UTC, merged